/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleSellIndexRouteImport } from './routes/$locale/sell/index'
import { Route as LocaleSearchIndexRouteImport } from './routes/$locale/search/index'
import { Route as LocaleOrdersIndexRouteImport } from './routes/$locale/orders/index'
import { Route as LocaleFavoritesIndexRouteImport } from './routes/$locale/favorites/index'
import { Route as LocaleCheckoutIndexRouteImport } from './routes/$locale/checkout/index'
import { Route as LocaleCartIndexRouteImport } from './routes/$locale/cart/index'
import { Route as LocaleShopsShopSlugRouteImport } from './routes/$locale/shops/$shopSlug'
import { Route as LocaleSellDashboardRouteImport } from './routes/$locale/sell/dashboard'
import { Route as LocalePromotionsSlugRouteImport } from './routes/$locale/promotions/$slug'
import { Route as LocaleProductsProductIdRouteImport } from './routes/$locale/products/$productId'
import { Route as LocaleOrdersOrderIdRouteImport } from './routes/$locale/orders/$orderId'
import { Route as LocaleCategoriesCategoryIdRouteImport } from './routes/$locale/categories/$categoryId'
import { Route as LocaleAdminShopsRouteImport } from './routes/$locale/admin/shops'
import { Route as LocaleSellProductsNewRouteImport } from './routes/$locale/sell/products/new'
import { Route as LocaleSellProductsProductIdRouteImport } from './routes/$locale/sell/products/$productId'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSellIndexRoute = LocaleSellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSearchIndexRoute = LocaleSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOrdersIndexRoute = LocaleOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFavoritesIndexRoute = LocaleFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCheckoutIndexRoute = LocaleCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCartIndexRoute = LocaleCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleShopsShopSlugRoute = LocaleShopsShopSlugRouteImport.update({
  id: '/shops/$shopSlug',
  path: '/shops/$shopSlug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSellDashboardRoute = LocaleSellDashboardRouteImport.update({
  id: '/sell/dashboard',
  path: '/sell/dashboard',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePromotionsSlugRoute = LocalePromotionsSlugRouteImport.update({
  id: '/promotions/$slug',
  path: '/promotions/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProductsProductIdRoute = LocaleProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOrdersOrderIdRoute = LocaleOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCategoriesCategoryIdRoute =
  LocaleCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleAdminShopsRoute = LocaleAdminShopsRouteImport.update({
  id: '/admin/shops',
  path: '/admin/shops',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSellProductsNewRoute = LocaleSellProductsNewRouteImport.update({
  id: '/sell/products/new',
  path: '/sell/products/new',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSellProductsProductIdRoute =
  LocaleSellProductsProductIdRouteImport.update({
    id: '/sell/products/$productId',
    path: '/sell/products/$productId',
    getParentRoute: () => LocaleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/shops': typeof LocaleAdminShopsRoute
  '/$locale/categories/$categoryId': typeof LocaleCategoriesCategoryIdRoute
  '/$locale/orders/$orderId': typeof LocaleOrdersOrderIdRoute
  '/$locale/products/$productId': typeof LocaleProductsProductIdRoute
  '/$locale/promotions/$slug': typeof LocalePromotionsSlugRoute
  '/$locale/sell/dashboard': typeof LocaleSellDashboardRoute
  '/$locale/shops/$shopSlug': typeof LocaleShopsShopSlugRoute
  '/$locale/cart/': typeof LocaleCartIndexRoute
  '/$locale/checkout/': typeof LocaleCheckoutIndexRoute
  '/$locale/favorites/': typeof LocaleFavoritesIndexRoute
  '/$locale/orders/': typeof LocaleOrdersIndexRoute
  '/$locale/search/': typeof LocaleSearchIndexRoute
  '/$locale/sell/': typeof LocaleSellIndexRoute
  '/$locale/sell/products/$productId': typeof LocaleSellProductsProductIdRoute
  '/$locale/sell/products/new': typeof LocaleSellProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/admin/shops': typeof LocaleAdminShopsRoute
  '/$locale/categories/$categoryId': typeof LocaleCategoriesCategoryIdRoute
  '/$locale/orders/$orderId': typeof LocaleOrdersOrderIdRoute
  '/$locale/products/$productId': typeof LocaleProductsProductIdRoute
  '/$locale/promotions/$slug': typeof LocalePromotionsSlugRoute
  '/$locale/sell/dashboard': typeof LocaleSellDashboardRoute
  '/$locale/shops/$shopSlug': typeof LocaleShopsShopSlugRoute
  '/$locale/cart': typeof LocaleCartIndexRoute
  '/$locale/checkout': typeof LocaleCheckoutIndexRoute
  '/$locale/favorites': typeof LocaleFavoritesIndexRoute
  '/$locale/orders': typeof LocaleOrdersIndexRoute
  '/$locale/search': typeof LocaleSearchIndexRoute
  '/$locale/sell': typeof LocaleSellIndexRoute
  '/$locale/sell/products/$productId': typeof LocaleSellProductsProductIdRoute
  '/$locale/sell/products/new': typeof LocaleSellProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/shops': typeof LocaleAdminShopsRoute
  '/$locale/categories/$categoryId': typeof LocaleCategoriesCategoryIdRoute
  '/$locale/orders/$orderId': typeof LocaleOrdersOrderIdRoute
  '/$locale/products/$productId': typeof LocaleProductsProductIdRoute
  '/$locale/promotions/$slug': typeof LocalePromotionsSlugRoute
  '/$locale/sell/dashboard': typeof LocaleSellDashboardRoute
  '/$locale/shops/$shopSlug': typeof LocaleShopsShopSlugRoute
  '/$locale/cart/': typeof LocaleCartIndexRoute
  '/$locale/checkout/': typeof LocaleCheckoutIndexRoute
  '/$locale/favorites/': typeof LocaleFavoritesIndexRoute
  '/$locale/orders/': typeof LocaleOrdersIndexRoute
  '/$locale/search/': typeof LocaleSearchIndexRoute
  '/$locale/sell/': typeof LocaleSellIndexRoute
  '/$locale/sell/products/$productId': typeof LocaleSellProductsProductIdRoute
  '/$locale/sell/products/new': typeof LocaleSellProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/admin/shops'
    | '/$locale/categories/$categoryId'
    | '/$locale/orders/$orderId'
    | '/$locale/products/$productId'
    | '/$locale/promotions/$slug'
    | '/$locale/sell/dashboard'
    | '/$locale/shops/$shopSlug'
    | '/$locale/cart/'
    | '/$locale/checkout/'
    | '/$locale/favorites/'
    | '/$locale/orders/'
    | '/$locale/search/'
    | '/$locale/sell/'
    | '/$locale/sell/products/$productId'
    | '/$locale/sell/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/admin/shops'
    | '/$locale/categories/$categoryId'
    | '/$locale/orders/$orderId'
    | '/$locale/products/$productId'
    | '/$locale/promotions/$slug'
    | '/$locale/sell/dashboard'
    | '/$locale/shops/$shopSlug'
    | '/$locale/cart'
    | '/$locale/checkout'
    | '/$locale/favorites'
    | '/$locale/orders'
    | '/$locale/search'
    | '/$locale/sell'
    | '/$locale/sell/products/$productId'
    | '/$locale/sell/products/new'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/admin/shops'
    | '/$locale/categories/$categoryId'
    | '/$locale/orders/$orderId'
    | '/$locale/products/$productId'
    | '/$locale/promotions/$slug'
    | '/$locale/sell/dashboard'
    | '/$locale/shops/$shopSlug'
    | '/$locale/cart/'
    | '/$locale/checkout/'
    | '/$locale/favorites/'
    | '/$locale/orders/'
    | '/$locale/search/'
    | '/$locale/sell/'
    | '/$locale/sell/products/$productId'
    | '/$locale/sell/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sell/': {
      id: '/$locale/sell/'
      path: '/sell'
      fullPath: '/$locale/sell/'
      preLoaderRoute: typeof LocaleSellIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/search/': {
      id: '/$locale/search/'
      path: '/search'
      fullPath: '/$locale/search/'
      preLoaderRoute: typeof LocaleSearchIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/orders/': {
      id: '/$locale/orders/'
      path: '/orders'
      fullPath: '/$locale/orders/'
      preLoaderRoute: typeof LocaleOrdersIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/favorites/': {
      id: '/$locale/favorites/'
      path: '/favorites'
      fullPath: '/$locale/favorites/'
      preLoaderRoute: typeof LocaleFavoritesIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/checkout/': {
      id: '/$locale/checkout/'
      path: '/checkout'
      fullPath: '/$locale/checkout/'
      preLoaderRoute: typeof LocaleCheckoutIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/cart/': {
      id: '/$locale/cart/'
      path: '/cart'
      fullPath: '/$locale/cart/'
      preLoaderRoute: typeof LocaleCartIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/shops/$shopSlug': {
      id: '/$locale/shops/$shopSlug'
      path: '/shops/$shopSlug'
      fullPath: '/$locale/shops/$shopSlug'
      preLoaderRoute: typeof LocaleShopsShopSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sell/dashboard': {
      id: '/$locale/sell/dashboard'
      path: '/sell/dashboard'
      fullPath: '/$locale/sell/dashboard'
      preLoaderRoute: typeof LocaleSellDashboardRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/promotions/$slug': {
      id: '/$locale/promotions/$slug'
      path: '/promotions/$slug'
      fullPath: '/$locale/promotions/$slug'
      preLoaderRoute: typeof LocalePromotionsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/products/$productId': {
      id: '/$locale/products/$productId'
      path: '/products/$productId'
      fullPath: '/$locale/products/$productId'
      preLoaderRoute: typeof LocaleProductsProductIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/orders/$orderId': {
      id: '/$locale/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$locale/orders/$orderId'
      preLoaderRoute: typeof LocaleOrdersOrderIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/categories/$categoryId': {
      id: '/$locale/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/$locale/categories/$categoryId'
      preLoaderRoute: typeof LocaleCategoriesCategoryIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/shops': {
      id: '/$locale/admin/shops'
      path: '/admin/shops'
      fullPath: '/$locale/admin/shops'
      preLoaderRoute: typeof LocaleAdminShopsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sell/products/new': {
      id: '/$locale/sell/products/new'
      path: '/sell/products/new'
      fullPath: '/$locale/sell/products/new'
      preLoaderRoute: typeof LocaleSellProductsNewRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sell/products/$productId': {
      id: '/$locale/sell/products/$productId'
      path: '/sell/products/$productId'
      fullPath: '/$locale/sell/products/$productId'
      preLoaderRoute: typeof LocaleSellProductsProductIdRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAdminShopsRoute: typeof LocaleAdminShopsRoute
  LocaleCategoriesCategoryIdRoute: typeof LocaleCategoriesCategoryIdRoute
  LocaleOrdersOrderIdRoute: typeof LocaleOrdersOrderIdRoute
  LocaleProductsProductIdRoute: typeof LocaleProductsProductIdRoute
  LocalePromotionsSlugRoute: typeof LocalePromotionsSlugRoute
  LocaleSellDashboardRoute: typeof LocaleSellDashboardRoute
  LocaleShopsShopSlugRoute: typeof LocaleShopsShopSlugRoute
  LocaleCartIndexRoute: typeof LocaleCartIndexRoute
  LocaleCheckoutIndexRoute: typeof LocaleCheckoutIndexRoute
  LocaleFavoritesIndexRoute: typeof LocaleFavoritesIndexRoute
  LocaleOrdersIndexRoute: typeof LocaleOrdersIndexRoute
  LocaleSearchIndexRoute: typeof LocaleSearchIndexRoute
  LocaleSellIndexRoute: typeof LocaleSellIndexRoute
  LocaleSellProductsProductIdRoute: typeof LocaleSellProductsProductIdRoute
  LocaleSellProductsNewRoute: typeof LocaleSellProductsNewRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAdminShopsRoute: LocaleAdminShopsRoute,
  LocaleCategoriesCategoryIdRoute: LocaleCategoriesCategoryIdRoute,
  LocaleOrdersOrderIdRoute: LocaleOrdersOrderIdRoute,
  LocaleProductsProductIdRoute: LocaleProductsProductIdRoute,
  LocalePromotionsSlugRoute: LocalePromotionsSlugRoute,
  LocaleSellDashboardRoute: LocaleSellDashboardRoute,
  LocaleShopsShopSlugRoute: LocaleShopsShopSlugRoute,
  LocaleCartIndexRoute: LocaleCartIndexRoute,
  LocaleCheckoutIndexRoute: LocaleCheckoutIndexRoute,
  LocaleFavoritesIndexRoute: LocaleFavoritesIndexRoute,
  LocaleOrdersIndexRoute: LocaleOrdersIndexRoute,
  LocaleSearchIndexRoute: LocaleSearchIndexRoute,
  LocaleSellIndexRoute: LocaleSellIndexRoute,
  LocaleSellProductsProductIdRoute: LocaleSellProductsProductIdRoute,
  LocaleSellProductsNewRoute: LocaleSellProductsNewRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
