/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocalestoreRouteRouteImport } from './routes/$locale/(store)/route'
import { Route as LocalesellerRouteRouteImport } from './routes/$locale/(seller)/route'
import { Route as LocaleadminRouteRouteImport } from './routes/$locale/(admin)/route'
import { Route as LocalestoreIndexRouteImport } from './routes/$locale/(store)/index'
import { Route as LocaleAuthVerifyEmailRouteImport } from './routes/$locale/auth/verify-email'
import { Route as LocaleAuthResetPasswordRouteImport } from './routes/$locale/auth/reset-password'
import { Route as LocaleAuthForgotPasswordRouteImport } from './routes/$locale/auth/forgot-password'
import { Route as LocalesellerSellRouteRouteImport } from './routes/$locale/(seller)/sell/route'
import { Route as LocaleadminAdminRouteRouteImport } from './routes/$locale/(admin)/admin/route'
import { Route as LocalestoreSearchIndexRouteImport } from './routes/$locale/(store)/search/index'
import { Route as LocalestoreOrdersIndexRouteImport } from './routes/$locale/(store)/orders/index'
import { Route as LocalestoreMessagesIndexRouteImport } from './routes/$locale/(store)/messages/index'
import { Route as LocalestoreFavoritesIndexRouteImport } from './routes/$locale/(store)/favorites/index'
import { Route as LocalestoreCheckoutIndexRouteImport } from './routes/$locale/(store)/checkout/index'
import { Route as LocalestoreCartIndexRouteImport } from './routes/$locale/(store)/cart/index'
import { Route as LocalesellerSellIndexRouteImport } from './routes/$locale/(seller)/sell/index'
import { Route as LocaleadminAdminIndexRouteImport } from './routes/$locale/(admin)/admin/index'
import { Route as LocalestoreShopsShopSlugRouteImport } from './routes/$locale/(store)/shops/$shopSlug'
import { Route as LocalestorePromotionsSlugRouteImport } from './routes/$locale/(store)/promotions/$slug'
import { Route as LocalestoreOrdersOrderIdRouteImport } from './routes/$locale/(store)/orders/$orderId'
import { Route as LocalestoreMessagesConversationIdRouteImport } from './routes/$locale/(store)/messages/$conversationId'
import { Route as LocalestoreListingsListingIdRouteImport } from './routes/$locale/(store)/listings/$listingId'
import { Route as LocalestoreLegalTermsRouteImport } from './routes/$locale/(store)/legal/terms'
import { Route as LocalestoreLegalSellerPolicyRouteImport } from './routes/$locale/(store)/legal/seller-policy'
import { Route as LocalestoreLegalReturnsRouteImport } from './routes/$locale/(store)/legal/returns'
import { Route as LocalestoreLegalPrivacyRouteImport } from './routes/$locale/(store)/legal/privacy'
import { Route as LocalestoreCategoriesCategoryIdRouteImport } from './routes/$locale/(store)/categories/$categoryId'
import { Route as LocalesellerSellStorefrontRouteImport } from './routes/$locale/(seller)/sell/storefront'
import { Route as LocalesellerSellRegisterRouteImport } from './routes/$locale/(seller)/sell/register'
import { Route as LocalesellerSellOnboardingRouteImport } from './routes/$locale/(seller)/sell/onboarding'
import { Route as LocalesellerSellDashboardRouteImport } from './routes/$locale/(seller)/sell/dashboard'
import { Route as LocaleadminAdminUsersRouteImport } from './routes/$locale/(admin)/admin/users'
import { Route as LocaleadminAdminShopsRouteImport } from './routes/$locale/(admin)/admin/shops'
import { Route as LocaleadminAdminPromotionsRouteImport } from './routes/$locale/(admin)/admin/promotions'
import { Route as LocaleadminAdminPromoCodesRouteImport } from './routes/$locale/(admin)/admin/promo-codes'
import { Route as LocaleadminAdminListingsRouteImport } from './routes/$locale/(admin)/admin/listings'
import { Route as LocaleadminAdminDashboardRouteImport } from './routes/$locale/(admin)/admin/dashboard'
import { Route as LocaleadminAdminCategoriesRouteImport } from './routes/$locale/(admin)/admin/categories'
import { Route as LocalesellerSellMessagesRouteRouteImport } from './routes/$locale/(seller)/sell/messages/route'
import { Route as LocalestorePaymentsSuccessIndexRouteImport } from './routes/$locale/(store)/payments/success/index'
import { Route as LocalesellerSellOrdersIndexRouteImport } from './routes/$locale/(seller)/sell/orders/index'
import { Route as LocalesellerSellMessagesIndexRouteImport } from './routes/$locale/(seller)/sell/messages/index'
import { Route as LocalesellerSellListingsIndexRouteImport } from './routes/$locale/(seller)/sell/listings/index'
import { Route as LocaleadminAdminOrdersIndexRouteImport } from './routes/$locale/(admin)/admin/orders/index'
import { Route as LocalestorePreviewListingsListingIdRouteImport } from './routes/$locale/(store)/preview/listings.$listingId'
import { Route as LocalestoreOrdersByTokenTokenRouteImport } from './routes/$locale/(store)/orders/by-token/$token'
import { Route as LocalesellerSellOrdersOrderIdRouteImport } from './routes/$locale/(seller)/sell/orders/$orderId'
import { Route as LocalesellerSellMessagesConversationIdRouteImport } from './routes/$locale/(seller)/sell/messages/$conversationId'
import { Route as LocalesellerSellListingsNewRouteImport } from './routes/$locale/(seller)/sell/listings/new'
import { Route as LocalesellerSellListingsListingIdRouteImport } from './routes/$locale/(seller)/sell/listings/$listingId'
import { Route as LocaleadminAdminOrdersOrderIdRouteImport } from './routes/$locale/(admin)/admin/orders/$orderId'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalestoreRouteRoute = LocalestoreRouteRouteImport.update({
  id: '/(store)',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalesellerRouteRoute = LocalesellerRouteRouteImport.update({
  id: '/(seller)',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleadminRouteRoute = LocaleadminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalestoreIndexRoute = LocalestoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalestoreRouteRoute,
} as any)
const LocaleAuthVerifyEmailRoute = LocaleAuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthResetPasswordRoute = LocaleAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthForgotPasswordRoute =
  LocaleAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocalesellerSellRouteRoute = LocalesellerSellRouteRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => LocalesellerRouteRoute,
} as any)
const LocaleadminAdminRouteRoute = LocaleadminAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LocaleadminRouteRoute,
} as any)
const LocalestoreSearchIndexRoute = LocalestoreSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => LocalestoreRouteRoute,
} as any)
const LocalestoreOrdersIndexRoute = LocalestoreOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => LocalestoreRouteRoute,
} as any)
const LocalestoreMessagesIndexRoute =
  LocalestoreMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreFavoritesIndexRoute =
  LocalestoreFavoritesIndexRouteImport.update({
    id: '/favorites/',
    path: '/favorites/',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreCheckoutIndexRoute =
  LocalestoreCheckoutIndexRouteImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreCartIndexRoute = LocalestoreCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => LocalestoreRouteRoute,
} as any)
const LocalesellerSellIndexRoute = LocalesellerSellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalesellerSellRouteRoute,
} as any)
const LocaleadminAdminIndexRoute = LocaleadminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleadminAdminRouteRoute,
} as any)
const LocalestoreShopsShopSlugRoute =
  LocalestoreShopsShopSlugRouteImport.update({
    id: '/shops/$shopSlug',
    path: '/shops/$shopSlug',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestorePromotionsSlugRoute =
  LocalestorePromotionsSlugRouteImport.update({
    id: '/promotions/$slug',
    path: '/promotions/$slug',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreOrdersOrderIdRoute =
  LocalestoreOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreMessagesConversationIdRoute =
  LocalestoreMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreListingsListingIdRoute =
  LocalestoreListingsListingIdRouteImport.update({
    id: '/listings/$listingId',
    path: '/listings/$listingId',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreLegalTermsRoute = LocalestoreLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => LocalestoreRouteRoute,
} as any)
const LocalestoreLegalSellerPolicyRoute =
  LocalestoreLegalSellerPolicyRouteImport.update({
    id: '/legal/seller-policy',
    path: '/legal/seller-policy',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreLegalReturnsRoute = LocalestoreLegalReturnsRouteImport.update({
  id: '/legal/returns',
  path: '/legal/returns',
  getParentRoute: () => LocalestoreRouteRoute,
} as any)
const LocalestoreLegalPrivacyRoute = LocalestoreLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => LocalestoreRouteRoute,
} as any)
const LocalestoreCategoriesCategoryIdRoute =
  LocalestoreCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalesellerSellStorefrontRoute =
  LocalesellerSellStorefrontRouteImport.update({
    id: '/storefront',
    path: '/storefront',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocalesellerSellRegisterRoute =
  LocalesellerSellRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocalesellerSellOnboardingRoute =
  LocalesellerSellOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocalesellerSellDashboardRoute =
  LocalesellerSellDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocaleadminAdminUsersRoute = LocaleadminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LocaleadminAdminRouteRoute,
} as any)
const LocaleadminAdminShopsRoute = LocaleadminAdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => LocaleadminAdminRouteRoute,
} as any)
const LocaleadminAdminPromotionsRoute =
  LocaleadminAdminPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)
const LocaleadminAdminPromoCodesRoute =
  LocaleadminAdminPromoCodesRouteImport.update({
    id: '/promo-codes',
    path: '/promo-codes',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)
const LocaleadminAdminListingsRoute =
  LocaleadminAdminListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)
const LocaleadminAdminDashboardRoute =
  LocaleadminAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)
const LocaleadminAdminCategoriesRoute =
  LocaleadminAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)
const LocalesellerSellMessagesRouteRoute =
  LocalesellerSellMessagesRouteRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocalestorePaymentsSuccessIndexRoute =
  LocalestorePaymentsSuccessIndexRouteImport.update({
    id: '/payments/success/',
    path: '/payments/success/',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalesellerSellOrdersIndexRoute =
  LocalesellerSellOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocalesellerSellMessagesIndexRoute =
  LocalesellerSellMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocalesellerSellMessagesRouteRoute,
  } as any)
const LocalesellerSellListingsIndexRoute =
  LocalesellerSellListingsIndexRouteImport.update({
    id: '/listings/',
    path: '/listings/',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocaleadminAdminOrdersIndexRoute =
  LocaleadminAdminOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)
const LocalestorePreviewListingsListingIdRoute =
  LocalestorePreviewListingsListingIdRouteImport.update({
    id: '/preview/listings/$listingId',
    path: '/preview/listings/$listingId',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreOrdersByTokenTokenRoute =
  LocalestoreOrdersByTokenTokenRouteImport.update({
    id: '/orders/by-token/$token',
    path: '/orders/by-token/$token',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalesellerSellOrdersOrderIdRoute =
  LocalesellerSellOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocalesellerSellMessagesConversationIdRoute =
  LocalesellerSellMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => LocalesellerSellMessagesRouteRoute,
  } as any)
const LocalesellerSellListingsNewRoute =
  LocalesellerSellListingsNewRouteImport.update({
    id: '/listings/new',
    path: '/listings/new',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocalesellerSellListingsListingIdRoute =
  LocalesellerSellListingsListingIdRouteImport.update({
    id: '/listings/$listingId',
    path: '/listings/$listingId',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocaleadminAdminOrdersOrderIdRoute =
  LocaleadminAdminOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocalestoreRouteRouteWithChildren
  '/$locale/admin': typeof LocaleadminAdminRouteRouteWithChildren
  '/$locale/sell': typeof LocalesellerSellRouteRouteWithChildren
  '/$locale/auth/forgot-password': typeof LocaleAuthForgotPasswordRoute
  '/$locale/auth/reset-password': typeof LocaleAuthResetPasswordRoute
  '/$locale/auth/verify-email': typeof LocaleAuthVerifyEmailRoute
  '/$locale/': typeof LocalestoreIndexRoute
  '/$locale/sell/messages': typeof LocalesellerSellMessagesRouteRouteWithChildren
  '/$locale/admin/categories': typeof LocaleadminAdminCategoriesRoute
  '/$locale/admin/dashboard': typeof LocaleadminAdminDashboardRoute
  '/$locale/admin/listings': typeof LocaleadminAdminListingsRoute
  '/$locale/admin/promo-codes': typeof LocaleadminAdminPromoCodesRoute
  '/$locale/admin/promotions': typeof LocaleadminAdminPromotionsRoute
  '/$locale/admin/shops': typeof LocaleadminAdminShopsRoute
  '/$locale/admin/users': typeof LocaleadminAdminUsersRoute
  '/$locale/sell/dashboard': typeof LocalesellerSellDashboardRoute
  '/$locale/sell/onboarding': typeof LocalesellerSellOnboardingRoute
  '/$locale/sell/register': typeof LocalesellerSellRegisterRoute
  '/$locale/sell/storefront': typeof LocalesellerSellStorefrontRoute
  '/$locale/categories/$categoryId': typeof LocalestoreCategoriesCategoryIdRoute
  '/$locale/legal/privacy': typeof LocalestoreLegalPrivacyRoute
  '/$locale/legal/returns': typeof LocalestoreLegalReturnsRoute
  '/$locale/legal/seller-policy': typeof LocalestoreLegalSellerPolicyRoute
  '/$locale/legal/terms': typeof LocalestoreLegalTermsRoute
  '/$locale/listings/$listingId': typeof LocalestoreListingsListingIdRoute
  '/$locale/messages/$conversationId': typeof LocalestoreMessagesConversationIdRoute
  '/$locale/orders/$orderId': typeof LocalestoreOrdersOrderIdRoute
  '/$locale/promotions/$slug': typeof LocalestorePromotionsSlugRoute
  '/$locale/shops/$shopSlug': typeof LocalestoreShopsShopSlugRoute
  '/$locale/admin/': typeof LocaleadminAdminIndexRoute
  '/$locale/sell/': typeof LocalesellerSellIndexRoute
  '/$locale/cart/': typeof LocalestoreCartIndexRoute
  '/$locale/checkout/': typeof LocalestoreCheckoutIndexRoute
  '/$locale/favorites/': typeof LocalestoreFavoritesIndexRoute
  '/$locale/messages/': typeof LocalestoreMessagesIndexRoute
  '/$locale/orders/': typeof LocalestoreOrdersIndexRoute
  '/$locale/search/': typeof LocalestoreSearchIndexRoute
  '/$locale/admin/orders/$orderId': typeof LocaleadminAdminOrdersOrderIdRoute
  '/$locale/sell/listings/$listingId': typeof LocalesellerSellListingsListingIdRoute
  '/$locale/sell/listings/new': typeof LocalesellerSellListingsNewRoute
  '/$locale/sell/messages/$conversationId': typeof LocalesellerSellMessagesConversationIdRoute
  '/$locale/sell/orders/$orderId': typeof LocalesellerSellOrdersOrderIdRoute
  '/$locale/orders/by-token/$token': typeof LocalestoreOrdersByTokenTokenRoute
  '/$locale/preview/listings/$listingId': typeof LocalestorePreviewListingsListingIdRoute
  '/$locale/admin/orders/': typeof LocaleadminAdminOrdersIndexRoute
  '/$locale/sell/listings/': typeof LocalesellerSellListingsIndexRoute
  '/$locale/sell/messages/': typeof LocalesellerSellMessagesIndexRoute
  '/$locale/sell/orders/': typeof LocalesellerSellOrdersIndexRoute
  '/$locale/payments/success/': typeof LocalestorePaymentsSuccessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocalestoreIndexRoute
  '/$locale/auth/forgot-password': typeof LocaleAuthForgotPasswordRoute
  '/$locale/auth/reset-password': typeof LocaleAuthResetPasswordRoute
  '/$locale/auth/verify-email': typeof LocaleAuthVerifyEmailRoute
  '/$locale/admin/categories': typeof LocaleadminAdminCategoriesRoute
  '/$locale/admin/dashboard': typeof LocaleadminAdminDashboardRoute
  '/$locale/admin/listings': typeof LocaleadminAdminListingsRoute
  '/$locale/admin/promo-codes': typeof LocaleadminAdminPromoCodesRoute
  '/$locale/admin/promotions': typeof LocaleadminAdminPromotionsRoute
  '/$locale/admin/shops': typeof LocaleadminAdminShopsRoute
  '/$locale/admin/users': typeof LocaleadminAdminUsersRoute
  '/$locale/sell/dashboard': typeof LocalesellerSellDashboardRoute
  '/$locale/sell/onboarding': typeof LocalesellerSellOnboardingRoute
  '/$locale/sell/register': typeof LocalesellerSellRegisterRoute
  '/$locale/sell/storefront': typeof LocalesellerSellStorefrontRoute
  '/$locale/categories/$categoryId': typeof LocalestoreCategoriesCategoryIdRoute
  '/$locale/legal/privacy': typeof LocalestoreLegalPrivacyRoute
  '/$locale/legal/returns': typeof LocalestoreLegalReturnsRoute
  '/$locale/legal/seller-policy': typeof LocalestoreLegalSellerPolicyRoute
  '/$locale/legal/terms': typeof LocalestoreLegalTermsRoute
  '/$locale/listings/$listingId': typeof LocalestoreListingsListingIdRoute
  '/$locale/messages/$conversationId': typeof LocalestoreMessagesConversationIdRoute
  '/$locale/orders/$orderId': typeof LocalestoreOrdersOrderIdRoute
  '/$locale/promotions/$slug': typeof LocalestorePromotionsSlugRoute
  '/$locale/shops/$shopSlug': typeof LocalestoreShopsShopSlugRoute
  '/$locale/admin': typeof LocaleadminAdminIndexRoute
  '/$locale/sell': typeof LocalesellerSellIndexRoute
  '/$locale/cart': typeof LocalestoreCartIndexRoute
  '/$locale/checkout': typeof LocalestoreCheckoutIndexRoute
  '/$locale/favorites': typeof LocalestoreFavoritesIndexRoute
  '/$locale/messages': typeof LocalestoreMessagesIndexRoute
  '/$locale/orders': typeof LocalestoreOrdersIndexRoute
  '/$locale/search': typeof LocalestoreSearchIndexRoute
  '/$locale/admin/orders/$orderId': typeof LocaleadminAdminOrdersOrderIdRoute
  '/$locale/sell/listings/$listingId': typeof LocalesellerSellListingsListingIdRoute
  '/$locale/sell/listings/new': typeof LocalesellerSellListingsNewRoute
  '/$locale/sell/messages/$conversationId': typeof LocalesellerSellMessagesConversationIdRoute
  '/$locale/sell/orders/$orderId': typeof LocalesellerSellOrdersOrderIdRoute
  '/$locale/orders/by-token/$token': typeof LocalestoreOrdersByTokenTokenRoute
  '/$locale/preview/listings/$listingId': typeof LocalestorePreviewListingsListingIdRoute
  '/$locale/admin/orders': typeof LocaleadminAdminOrdersIndexRoute
  '/$locale/sell/listings': typeof LocalesellerSellListingsIndexRoute
  '/$locale/sell/messages': typeof LocalesellerSellMessagesIndexRoute
  '/$locale/sell/orders': typeof LocalesellerSellOrdersIndexRoute
  '/$locale/payments/success': typeof LocalestorePaymentsSuccessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/(admin)': typeof LocaleadminRouteRouteWithChildren
  '/$locale/(seller)': typeof LocalesellerRouteRouteWithChildren
  '/$locale/(store)': typeof LocalestoreRouteRouteWithChildren
  '/$locale/(admin)/admin': typeof LocaleadminAdminRouteRouteWithChildren
  '/$locale/(seller)/sell': typeof LocalesellerSellRouteRouteWithChildren
  '/$locale/auth/forgot-password': typeof LocaleAuthForgotPasswordRoute
  '/$locale/auth/reset-password': typeof LocaleAuthResetPasswordRoute
  '/$locale/auth/verify-email': typeof LocaleAuthVerifyEmailRoute
  '/$locale/(store)/': typeof LocalestoreIndexRoute
  '/$locale/(seller)/sell/messages': typeof LocalesellerSellMessagesRouteRouteWithChildren
  '/$locale/(admin)/admin/categories': typeof LocaleadminAdminCategoriesRoute
  '/$locale/(admin)/admin/dashboard': typeof LocaleadminAdminDashboardRoute
  '/$locale/(admin)/admin/listings': typeof LocaleadminAdminListingsRoute
  '/$locale/(admin)/admin/promo-codes': typeof LocaleadminAdminPromoCodesRoute
  '/$locale/(admin)/admin/promotions': typeof LocaleadminAdminPromotionsRoute
  '/$locale/(admin)/admin/shops': typeof LocaleadminAdminShopsRoute
  '/$locale/(admin)/admin/users': typeof LocaleadminAdminUsersRoute
  '/$locale/(seller)/sell/dashboard': typeof LocalesellerSellDashboardRoute
  '/$locale/(seller)/sell/onboarding': typeof LocalesellerSellOnboardingRoute
  '/$locale/(seller)/sell/register': typeof LocalesellerSellRegisterRoute
  '/$locale/(seller)/sell/storefront': typeof LocalesellerSellStorefrontRoute
  '/$locale/(store)/categories/$categoryId': typeof LocalestoreCategoriesCategoryIdRoute
  '/$locale/(store)/legal/privacy': typeof LocalestoreLegalPrivacyRoute
  '/$locale/(store)/legal/returns': typeof LocalestoreLegalReturnsRoute
  '/$locale/(store)/legal/seller-policy': typeof LocalestoreLegalSellerPolicyRoute
  '/$locale/(store)/legal/terms': typeof LocalestoreLegalTermsRoute
  '/$locale/(store)/listings/$listingId': typeof LocalestoreListingsListingIdRoute
  '/$locale/(store)/messages/$conversationId': typeof LocalestoreMessagesConversationIdRoute
  '/$locale/(store)/orders/$orderId': typeof LocalestoreOrdersOrderIdRoute
  '/$locale/(store)/promotions/$slug': typeof LocalestorePromotionsSlugRoute
  '/$locale/(store)/shops/$shopSlug': typeof LocalestoreShopsShopSlugRoute
  '/$locale/(admin)/admin/': typeof LocaleadminAdminIndexRoute
  '/$locale/(seller)/sell/': typeof LocalesellerSellIndexRoute
  '/$locale/(store)/cart/': typeof LocalestoreCartIndexRoute
  '/$locale/(store)/checkout/': typeof LocalestoreCheckoutIndexRoute
  '/$locale/(store)/favorites/': typeof LocalestoreFavoritesIndexRoute
  '/$locale/(store)/messages/': typeof LocalestoreMessagesIndexRoute
  '/$locale/(store)/orders/': typeof LocalestoreOrdersIndexRoute
  '/$locale/(store)/search/': typeof LocalestoreSearchIndexRoute
  '/$locale/(admin)/admin/orders/$orderId': typeof LocaleadminAdminOrdersOrderIdRoute
  '/$locale/(seller)/sell/listings/$listingId': typeof LocalesellerSellListingsListingIdRoute
  '/$locale/(seller)/sell/listings/new': typeof LocalesellerSellListingsNewRoute
  '/$locale/(seller)/sell/messages/$conversationId': typeof LocalesellerSellMessagesConversationIdRoute
  '/$locale/(seller)/sell/orders/$orderId': typeof LocalesellerSellOrdersOrderIdRoute
  '/$locale/(store)/orders/by-token/$token': typeof LocalestoreOrdersByTokenTokenRoute
  '/$locale/(store)/preview/listings/$listingId': typeof LocalestorePreviewListingsListingIdRoute
  '/$locale/(admin)/admin/orders/': typeof LocaleadminAdminOrdersIndexRoute
  '/$locale/(seller)/sell/listings/': typeof LocalesellerSellListingsIndexRoute
  '/$locale/(seller)/sell/messages/': typeof LocalesellerSellMessagesIndexRoute
  '/$locale/(seller)/sell/orders/': typeof LocalesellerSellOrdersIndexRoute
  '/$locale/(store)/payments/success/': typeof LocalestorePaymentsSuccessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/admin'
    | '/$locale/sell'
    | '/$locale/auth/forgot-password'
    | '/$locale/auth/reset-password'
    | '/$locale/auth/verify-email'
    | '/$locale/'
    | '/$locale/sell/messages'
    | '/$locale/admin/categories'
    | '/$locale/admin/dashboard'
    | '/$locale/admin/listings'
    | '/$locale/admin/promo-codes'
    | '/$locale/admin/promotions'
    | '/$locale/admin/shops'
    | '/$locale/admin/users'
    | '/$locale/sell/dashboard'
    | '/$locale/sell/onboarding'
    | '/$locale/sell/register'
    | '/$locale/sell/storefront'
    | '/$locale/categories/$categoryId'
    | '/$locale/legal/privacy'
    | '/$locale/legal/returns'
    | '/$locale/legal/seller-policy'
    | '/$locale/legal/terms'
    | '/$locale/listings/$listingId'
    | '/$locale/messages/$conversationId'
    | '/$locale/orders/$orderId'
    | '/$locale/promotions/$slug'
    | '/$locale/shops/$shopSlug'
    | '/$locale/admin/'
    | '/$locale/sell/'
    | '/$locale/cart/'
    | '/$locale/checkout/'
    | '/$locale/favorites/'
    | '/$locale/messages/'
    | '/$locale/orders/'
    | '/$locale/search/'
    | '/$locale/admin/orders/$orderId'
    | '/$locale/sell/listings/$listingId'
    | '/$locale/sell/listings/new'
    | '/$locale/sell/messages/$conversationId'
    | '/$locale/sell/orders/$orderId'
    | '/$locale/orders/by-token/$token'
    | '/$locale/preview/listings/$listingId'
    | '/$locale/admin/orders/'
    | '/$locale/sell/listings/'
    | '/$locale/sell/messages/'
    | '/$locale/sell/orders/'
    | '/$locale/payments/success/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/auth/forgot-password'
    | '/$locale/auth/reset-password'
    | '/$locale/auth/verify-email'
    | '/$locale/admin/categories'
    | '/$locale/admin/dashboard'
    | '/$locale/admin/listings'
    | '/$locale/admin/promo-codes'
    | '/$locale/admin/promotions'
    | '/$locale/admin/shops'
    | '/$locale/admin/users'
    | '/$locale/sell/dashboard'
    | '/$locale/sell/onboarding'
    | '/$locale/sell/register'
    | '/$locale/sell/storefront'
    | '/$locale/categories/$categoryId'
    | '/$locale/legal/privacy'
    | '/$locale/legal/returns'
    | '/$locale/legal/seller-policy'
    | '/$locale/legal/terms'
    | '/$locale/listings/$listingId'
    | '/$locale/messages/$conversationId'
    | '/$locale/orders/$orderId'
    | '/$locale/promotions/$slug'
    | '/$locale/shops/$shopSlug'
    | '/$locale/admin'
    | '/$locale/sell'
    | '/$locale/cart'
    | '/$locale/checkout'
    | '/$locale/favorites'
    | '/$locale/messages'
    | '/$locale/orders'
    | '/$locale/search'
    | '/$locale/admin/orders/$orderId'
    | '/$locale/sell/listings/$listingId'
    | '/$locale/sell/listings/new'
    | '/$locale/sell/messages/$conversationId'
    | '/$locale/sell/orders/$orderId'
    | '/$locale/orders/by-token/$token'
    | '/$locale/preview/listings/$listingId'
    | '/$locale/admin/orders'
    | '/$locale/sell/listings'
    | '/$locale/sell/messages'
    | '/$locale/sell/orders'
    | '/$locale/payments/success'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/(admin)'
    | '/$locale/(seller)'
    | '/$locale/(store)'
    | '/$locale/(admin)/admin'
    | '/$locale/(seller)/sell'
    | '/$locale/auth/forgot-password'
    | '/$locale/auth/reset-password'
    | '/$locale/auth/verify-email'
    | '/$locale/(store)/'
    | '/$locale/(seller)/sell/messages'
    | '/$locale/(admin)/admin/categories'
    | '/$locale/(admin)/admin/dashboard'
    | '/$locale/(admin)/admin/listings'
    | '/$locale/(admin)/admin/promo-codes'
    | '/$locale/(admin)/admin/promotions'
    | '/$locale/(admin)/admin/shops'
    | '/$locale/(admin)/admin/users'
    | '/$locale/(seller)/sell/dashboard'
    | '/$locale/(seller)/sell/onboarding'
    | '/$locale/(seller)/sell/register'
    | '/$locale/(seller)/sell/storefront'
    | '/$locale/(store)/categories/$categoryId'
    | '/$locale/(store)/legal/privacy'
    | '/$locale/(store)/legal/returns'
    | '/$locale/(store)/legal/seller-policy'
    | '/$locale/(store)/legal/terms'
    | '/$locale/(store)/listings/$listingId'
    | '/$locale/(store)/messages/$conversationId'
    | '/$locale/(store)/orders/$orderId'
    | '/$locale/(store)/promotions/$slug'
    | '/$locale/(store)/shops/$shopSlug'
    | '/$locale/(admin)/admin/'
    | '/$locale/(seller)/sell/'
    | '/$locale/(store)/cart/'
    | '/$locale/(store)/checkout/'
    | '/$locale/(store)/favorites/'
    | '/$locale/(store)/messages/'
    | '/$locale/(store)/orders/'
    | '/$locale/(store)/search/'
    | '/$locale/(admin)/admin/orders/$orderId'
    | '/$locale/(seller)/sell/listings/$listingId'
    | '/$locale/(seller)/sell/listings/new'
    | '/$locale/(seller)/sell/messages/$conversationId'
    | '/$locale/(seller)/sell/orders/$orderId'
    | '/$locale/(store)/orders/by-token/$token'
    | '/$locale/(store)/preview/listings/$listingId'
    | '/$locale/(admin)/admin/orders/'
    | '/$locale/(seller)/sell/listings/'
    | '/$locale/(seller)/sell/messages/'
    | '/$locale/(seller)/sell/orders/'
    | '/$locale/(store)/payments/success/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(store)': {
      id: '/$locale/(store)'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocalestoreRouteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/(seller)': {
      id: '/$locale/(seller)'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocalesellerRouteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/(admin)': {
      id: '/$locale/(admin)'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleadminRouteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/(store)/': {
      id: '/$locale/(store)/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocalestoreIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/auth/verify-email': {
      id: '/$locale/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/$locale/auth/verify-email'
      preLoaderRoute: typeof LocaleAuthVerifyEmailRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/reset-password': {
      id: '/$locale/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/$locale/auth/reset-password'
      preLoaderRoute: typeof LocaleAuthResetPasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/forgot-password': {
      id: '/$locale/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/$locale/auth/forgot-password'
      preLoaderRoute: typeof LocaleAuthForgotPasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/(seller)/sell': {
      id: '/$locale/(seller)/sell'
      path: '/sell'
      fullPath: '/$locale/sell'
      preLoaderRoute: typeof LocalesellerSellRouteRouteImport
      parentRoute: typeof LocalesellerRouteRoute
    }
    '/$locale/(admin)/admin': {
      id: '/$locale/(admin)/admin'
      path: '/admin'
      fullPath: '/$locale/admin'
      preLoaderRoute: typeof LocaleadminAdminRouteRouteImport
      parentRoute: typeof LocaleadminRouteRoute
    }
    '/$locale/(store)/search/': {
      id: '/$locale/(store)/search/'
      path: '/search'
      fullPath: '/$locale/search/'
      preLoaderRoute: typeof LocalestoreSearchIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/orders/': {
      id: '/$locale/(store)/orders/'
      path: '/orders'
      fullPath: '/$locale/orders/'
      preLoaderRoute: typeof LocalestoreOrdersIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/messages/': {
      id: '/$locale/(store)/messages/'
      path: '/messages'
      fullPath: '/$locale/messages/'
      preLoaderRoute: typeof LocalestoreMessagesIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/favorites/': {
      id: '/$locale/(store)/favorites/'
      path: '/favorites'
      fullPath: '/$locale/favorites/'
      preLoaderRoute: typeof LocalestoreFavoritesIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/checkout/': {
      id: '/$locale/(store)/checkout/'
      path: '/checkout'
      fullPath: '/$locale/checkout/'
      preLoaderRoute: typeof LocalestoreCheckoutIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/cart/': {
      id: '/$locale/(store)/cart/'
      path: '/cart'
      fullPath: '/$locale/cart/'
      preLoaderRoute: typeof LocalestoreCartIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(seller)/sell/': {
      id: '/$locale/(seller)/sell/'
      path: '/'
      fullPath: '/$locale/sell/'
      preLoaderRoute: typeof LocalesellerSellIndexRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(admin)/admin/': {
      id: '/$locale/(admin)/admin/'
      path: '/'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleadminAdminIndexRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(store)/shops/$shopSlug': {
      id: '/$locale/(store)/shops/$shopSlug'
      path: '/shops/$shopSlug'
      fullPath: '/$locale/shops/$shopSlug'
      preLoaderRoute: typeof LocalestoreShopsShopSlugRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/promotions/$slug': {
      id: '/$locale/(store)/promotions/$slug'
      path: '/promotions/$slug'
      fullPath: '/$locale/promotions/$slug'
      preLoaderRoute: typeof LocalestorePromotionsSlugRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/orders/$orderId': {
      id: '/$locale/(store)/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$locale/orders/$orderId'
      preLoaderRoute: typeof LocalestoreOrdersOrderIdRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/messages/$conversationId': {
      id: '/$locale/(store)/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/$locale/messages/$conversationId'
      preLoaderRoute: typeof LocalestoreMessagesConversationIdRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/listings/$listingId': {
      id: '/$locale/(store)/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/$locale/listings/$listingId'
      preLoaderRoute: typeof LocalestoreListingsListingIdRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/legal/terms': {
      id: '/$locale/(store)/legal/terms'
      path: '/legal/terms'
      fullPath: '/$locale/legal/terms'
      preLoaderRoute: typeof LocalestoreLegalTermsRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/legal/seller-policy': {
      id: '/$locale/(store)/legal/seller-policy'
      path: '/legal/seller-policy'
      fullPath: '/$locale/legal/seller-policy'
      preLoaderRoute: typeof LocalestoreLegalSellerPolicyRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/legal/returns': {
      id: '/$locale/(store)/legal/returns'
      path: '/legal/returns'
      fullPath: '/$locale/legal/returns'
      preLoaderRoute: typeof LocalestoreLegalReturnsRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/legal/privacy': {
      id: '/$locale/(store)/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/$locale/legal/privacy'
      preLoaderRoute: typeof LocalestoreLegalPrivacyRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/categories/$categoryId': {
      id: '/$locale/(store)/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/$locale/categories/$categoryId'
      preLoaderRoute: typeof LocalestoreCategoriesCategoryIdRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(seller)/sell/storefront': {
      id: '/$locale/(seller)/sell/storefront'
      path: '/storefront'
      fullPath: '/$locale/sell/storefront'
      preLoaderRoute: typeof LocalesellerSellStorefrontRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(seller)/sell/register': {
      id: '/$locale/(seller)/sell/register'
      path: '/register'
      fullPath: '/$locale/sell/register'
      preLoaderRoute: typeof LocalesellerSellRegisterRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(seller)/sell/onboarding': {
      id: '/$locale/(seller)/sell/onboarding'
      path: '/onboarding'
      fullPath: '/$locale/sell/onboarding'
      preLoaderRoute: typeof LocalesellerSellOnboardingRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(seller)/sell/dashboard': {
      id: '/$locale/(seller)/sell/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/sell/dashboard'
      preLoaderRoute: typeof LocalesellerSellDashboardRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(admin)/admin/users': {
      id: '/$locale/(admin)/admin/users'
      path: '/users'
      fullPath: '/$locale/admin/users'
      preLoaderRoute: typeof LocaleadminAdminUsersRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(admin)/admin/shops': {
      id: '/$locale/(admin)/admin/shops'
      path: '/shops'
      fullPath: '/$locale/admin/shops'
      preLoaderRoute: typeof LocaleadminAdminShopsRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(admin)/admin/promotions': {
      id: '/$locale/(admin)/admin/promotions'
      path: '/promotions'
      fullPath: '/$locale/admin/promotions'
      preLoaderRoute: typeof LocaleadminAdminPromotionsRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(admin)/admin/promo-codes': {
      id: '/$locale/(admin)/admin/promo-codes'
      path: '/promo-codes'
      fullPath: '/$locale/admin/promo-codes'
      preLoaderRoute: typeof LocaleadminAdminPromoCodesRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(admin)/admin/listings': {
      id: '/$locale/(admin)/admin/listings'
      path: '/listings'
      fullPath: '/$locale/admin/listings'
      preLoaderRoute: typeof LocaleadminAdminListingsRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(admin)/admin/dashboard': {
      id: '/$locale/(admin)/admin/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/admin/dashboard'
      preLoaderRoute: typeof LocaleadminAdminDashboardRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(admin)/admin/categories': {
      id: '/$locale/(admin)/admin/categories'
      path: '/categories'
      fullPath: '/$locale/admin/categories'
      preLoaderRoute: typeof LocaleadminAdminCategoriesRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(seller)/sell/messages': {
      id: '/$locale/(seller)/sell/messages'
      path: '/messages'
      fullPath: '/$locale/sell/messages'
      preLoaderRoute: typeof LocalesellerSellMessagesRouteRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(store)/payments/success/': {
      id: '/$locale/(store)/payments/success/'
      path: '/payments/success'
      fullPath: '/$locale/payments/success/'
      preLoaderRoute: typeof LocalestorePaymentsSuccessIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(seller)/sell/orders/': {
      id: '/$locale/(seller)/sell/orders/'
      path: '/orders'
      fullPath: '/$locale/sell/orders/'
      preLoaderRoute: typeof LocalesellerSellOrdersIndexRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(seller)/sell/messages/': {
      id: '/$locale/(seller)/sell/messages/'
      path: '/'
      fullPath: '/$locale/sell/messages/'
      preLoaderRoute: typeof LocalesellerSellMessagesIndexRouteImport
      parentRoute: typeof LocalesellerSellMessagesRouteRoute
    }
    '/$locale/(seller)/sell/listings/': {
      id: '/$locale/(seller)/sell/listings/'
      path: '/listings'
      fullPath: '/$locale/sell/listings/'
      preLoaderRoute: typeof LocalesellerSellListingsIndexRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(admin)/admin/orders/': {
      id: '/$locale/(admin)/admin/orders/'
      path: '/orders'
      fullPath: '/$locale/admin/orders/'
      preLoaderRoute: typeof LocaleadminAdminOrdersIndexRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(store)/preview/listings/$listingId': {
      id: '/$locale/(store)/preview/listings/$listingId'
      path: '/preview/listings/$listingId'
      fullPath: '/$locale/preview/listings/$listingId'
      preLoaderRoute: typeof LocalestorePreviewListingsListingIdRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/orders/by-token/$token': {
      id: '/$locale/(store)/orders/by-token/$token'
      path: '/orders/by-token/$token'
      fullPath: '/$locale/orders/by-token/$token'
      preLoaderRoute: typeof LocalestoreOrdersByTokenTokenRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(seller)/sell/orders/$orderId': {
      id: '/$locale/(seller)/sell/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$locale/sell/orders/$orderId'
      preLoaderRoute: typeof LocalesellerSellOrdersOrderIdRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(seller)/sell/messages/$conversationId': {
      id: '/$locale/(seller)/sell/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/$locale/sell/messages/$conversationId'
      preLoaderRoute: typeof LocalesellerSellMessagesConversationIdRouteImport
      parentRoute: typeof LocalesellerSellMessagesRouteRoute
    }
    '/$locale/(seller)/sell/listings/new': {
      id: '/$locale/(seller)/sell/listings/new'
      path: '/listings/new'
      fullPath: '/$locale/sell/listings/new'
      preLoaderRoute: typeof LocalesellerSellListingsNewRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(seller)/sell/listings/$listingId': {
      id: '/$locale/(seller)/sell/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/$locale/sell/listings/$listingId'
      preLoaderRoute: typeof LocalesellerSellListingsListingIdRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(admin)/admin/orders/$orderId': {
      id: '/$locale/(admin)/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$locale/admin/orders/$orderId'
      preLoaderRoute: typeof LocaleadminAdminOrdersOrderIdRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
  }
}

interface LocaleadminAdminRouteRouteChildren {
  LocaleadminAdminCategoriesRoute: typeof LocaleadminAdminCategoriesRoute
  LocaleadminAdminDashboardRoute: typeof LocaleadminAdminDashboardRoute
  LocaleadminAdminListingsRoute: typeof LocaleadminAdminListingsRoute
  LocaleadminAdminPromoCodesRoute: typeof LocaleadminAdminPromoCodesRoute
  LocaleadminAdminPromotionsRoute: typeof LocaleadminAdminPromotionsRoute
  LocaleadminAdminShopsRoute: typeof LocaleadminAdminShopsRoute
  LocaleadminAdminUsersRoute: typeof LocaleadminAdminUsersRoute
  LocaleadminAdminIndexRoute: typeof LocaleadminAdminIndexRoute
  LocaleadminAdminOrdersOrderIdRoute: typeof LocaleadminAdminOrdersOrderIdRoute
  LocaleadminAdminOrdersIndexRoute: typeof LocaleadminAdminOrdersIndexRoute
}

const LocaleadminAdminRouteRouteChildren: LocaleadminAdminRouteRouteChildren = {
  LocaleadminAdminCategoriesRoute: LocaleadminAdminCategoriesRoute,
  LocaleadminAdminDashboardRoute: LocaleadminAdminDashboardRoute,
  LocaleadminAdminListingsRoute: LocaleadminAdminListingsRoute,
  LocaleadminAdminPromoCodesRoute: LocaleadminAdminPromoCodesRoute,
  LocaleadminAdminPromotionsRoute: LocaleadminAdminPromotionsRoute,
  LocaleadminAdminShopsRoute: LocaleadminAdminShopsRoute,
  LocaleadminAdminUsersRoute: LocaleadminAdminUsersRoute,
  LocaleadminAdminIndexRoute: LocaleadminAdminIndexRoute,
  LocaleadminAdminOrdersOrderIdRoute: LocaleadminAdminOrdersOrderIdRoute,
  LocaleadminAdminOrdersIndexRoute: LocaleadminAdminOrdersIndexRoute,
}

const LocaleadminAdminRouteRouteWithChildren =
  LocaleadminAdminRouteRoute._addFileChildren(
    LocaleadminAdminRouteRouteChildren,
  )

interface LocaleadminRouteRouteChildren {
  LocaleadminAdminRouteRoute: typeof LocaleadminAdminRouteRouteWithChildren
}

const LocaleadminRouteRouteChildren: LocaleadminRouteRouteChildren = {
  LocaleadminAdminRouteRoute: LocaleadminAdminRouteRouteWithChildren,
}

const LocaleadminRouteRouteWithChildren =
  LocaleadminRouteRoute._addFileChildren(LocaleadminRouteRouteChildren)

interface LocalesellerSellMessagesRouteRouteChildren {
  LocalesellerSellMessagesConversationIdRoute: typeof LocalesellerSellMessagesConversationIdRoute
  LocalesellerSellMessagesIndexRoute: typeof LocalesellerSellMessagesIndexRoute
}

const LocalesellerSellMessagesRouteRouteChildren: LocalesellerSellMessagesRouteRouteChildren =
  {
    LocalesellerSellMessagesConversationIdRoute:
      LocalesellerSellMessagesConversationIdRoute,
    LocalesellerSellMessagesIndexRoute: LocalesellerSellMessagesIndexRoute,
  }

const LocalesellerSellMessagesRouteRouteWithChildren =
  LocalesellerSellMessagesRouteRoute._addFileChildren(
    LocalesellerSellMessagesRouteRouteChildren,
  )

interface LocalesellerSellRouteRouteChildren {
  LocalesellerSellMessagesRouteRoute: typeof LocalesellerSellMessagesRouteRouteWithChildren
  LocalesellerSellDashboardRoute: typeof LocalesellerSellDashboardRoute
  LocalesellerSellOnboardingRoute: typeof LocalesellerSellOnboardingRoute
  LocalesellerSellRegisterRoute: typeof LocalesellerSellRegisterRoute
  LocalesellerSellStorefrontRoute: typeof LocalesellerSellStorefrontRoute
  LocalesellerSellIndexRoute: typeof LocalesellerSellIndexRoute
  LocalesellerSellListingsListingIdRoute: typeof LocalesellerSellListingsListingIdRoute
  LocalesellerSellListingsNewRoute: typeof LocalesellerSellListingsNewRoute
  LocalesellerSellOrdersOrderIdRoute: typeof LocalesellerSellOrdersOrderIdRoute
  LocalesellerSellListingsIndexRoute: typeof LocalesellerSellListingsIndexRoute
  LocalesellerSellOrdersIndexRoute: typeof LocalesellerSellOrdersIndexRoute
}

const LocalesellerSellRouteRouteChildren: LocalesellerSellRouteRouteChildren = {
  LocalesellerSellMessagesRouteRoute:
    LocalesellerSellMessagesRouteRouteWithChildren,
  LocalesellerSellDashboardRoute: LocalesellerSellDashboardRoute,
  LocalesellerSellOnboardingRoute: LocalesellerSellOnboardingRoute,
  LocalesellerSellRegisterRoute: LocalesellerSellRegisterRoute,
  LocalesellerSellStorefrontRoute: LocalesellerSellStorefrontRoute,
  LocalesellerSellIndexRoute: LocalesellerSellIndexRoute,
  LocalesellerSellListingsListingIdRoute:
    LocalesellerSellListingsListingIdRoute,
  LocalesellerSellListingsNewRoute: LocalesellerSellListingsNewRoute,
  LocalesellerSellOrdersOrderIdRoute: LocalesellerSellOrdersOrderIdRoute,
  LocalesellerSellListingsIndexRoute: LocalesellerSellListingsIndexRoute,
  LocalesellerSellOrdersIndexRoute: LocalesellerSellOrdersIndexRoute,
}

const LocalesellerSellRouteRouteWithChildren =
  LocalesellerSellRouteRoute._addFileChildren(
    LocalesellerSellRouteRouteChildren,
  )

interface LocalesellerRouteRouteChildren {
  LocalesellerSellRouteRoute: typeof LocalesellerSellRouteRouteWithChildren
}

const LocalesellerRouteRouteChildren: LocalesellerRouteRouteChildren = {
  LocalesellerSellRouteRoute: LocalesellerSellRouteRouteWithChildren,
}

const LocalesellerRouteRouteWithChildren =
  LocalesellerRouteRoute._addFileChildren(LocalesellerRouteRouteChildren)

interface LocalestoreRouteRouteChildren {
  LocalestoreIndexRoute: typeof LocalestoreIndexRoute
  LocalestoreCategoriesCategoryIdRoute: typeof LocalestoreCategoriesCategoryIdRoute
  LocalestoreLegalPrivacyRoute: typeof LocalestoreLegalPrivacyRoute
  LocalestoreLegalReturnsRoute: typeof LocalestoreLegalReturnsRoute
  LocalestoreLegalSellerPolicyRoute: typeof LocalestoreLegalSellerPolicyRoute
  LocalestoreLegalTermsRoute: typeof LocalestoreLegalTermsRoute
  LocalestoreListingsListingIdRoute: typeof LocalestoreListingsListingIdRoute
  LocalestoreMessagesConversationIdRoute: typeof LocalestoreMessagesConversationIdRoute
  LocalestoreOrdersOrderIdRoute: typeof LocalestoreOrdersOrderIdRoute
  LocalestorePromotionsSlugRoute: typeof LocalestorePromotionsSlugRoute
  LocalestoreShopsShopSlugRoute: typeof LocalestoreShopsShopSlugRoute
  LocalestoreCartIndexRoute: typeof LocalestoreCartIndexRoute
  LocalestoreCheckoutIndexRoute: typeof LocalestoreCheckoutIndexRoute
  LocalestoreFavoritesIndexRoute: typeof LocalestoreFavoritesIndexRoute
  LocalestoreMessagesIndexRoute: typeof LocalestoreMessagesIndexRoute
  LocalestoreOrdersIndexRoute: typeof LocalestoreOrdersIndexRoute
  LocalestoreSearchIndexRoute: typeof LocalestoreSearchIndexRoute
  LocalestoreOrdersByTokenTokenRoute: typeof LocalestoreOrdersByTokenTokenRoute
  LocalestorePreviewListingsListingIdRoute: typeof LocalestorePreviewListingsListingIdRoute
  LocalestorePaymentsSuccessIndexRoute: typeof LocalestorePaymentsSuccessIndexRoute
}

const LocalestoreRouteRouteChildren: LocalestoreRouteRouteChildren = {
  LocalestoreIndexRoute: LocalestoreIndexRoute,
  LocalestoreCategoriesCategoryIdRoute: LocalestoreCategoriesCategoryIdRoute,
  LocalestoreLegalPrivacyRoute: LocalestoreLegalPrivacyRoute,
  LocalestoreLegalReturnsRoute: LocalestoreLegalReturnsRoute,
  LocalestoreLegalSellerPolicyRoute: LocalestoreLegalSellerPolicyRoute,
  LocalestoreLegalTermsRoute: LocalestoreLegalTermsRoute,
  LocalestoreListingsListingIdRoute: LocalestoreListingsListingIdRoute,
  LocalestoreMessagesConversationIdRoute:
    LocalestoreMessagesConversationIdRoute,
  LocalestoreOrdersOrderIdRoute: LocalestoreOrdersOrderIdRoute,
  LocalestorePromotionsSlugRoute: LocalestorePromotionsSlugRoute,
  LocalestoreShopsShopSlugRoute: LocalestoreShopsShopSlugRoute,
  LocalestoreCartIndexRoute: LocalestoreCartIndexRoute,
  LocalestoreCheckoutIndexRoute: LocalestoreCheckoutIndexRoute,
  LocalestoreFavoritesIndexRoute: LocalestoreFavoritesIndexRoute,
  LocalestoreMessagesIndexRoute: LocalestoreMessagesIndexRoute,
  LocalestoreOrdersIndexRoute: LocalestoreOrdersIndexRoute,
  LocalestoreSearchIndexRoute: LocalestoreSearchIndexRoute,
  LocalestoreOrdersByTokenTokenRoute: LocalestoreOrdersByTokenTokenRoute,
  LocalestorePreviewListingsListingIdRoute:
    LocalestorePreviewListingsListingIdRoute,
  LocalestorePaymentsSuccessIndexRoute: LocalestorePaymentsSuccessIndexRoute,
}

const LocalestoreRouteRouteWithChildren =
  LocalestoreRouteRoute._addFileChildren(LocalestoreRouteRouteChildren)

interface LocaleRouteChildren {
  LocaleadminRouteRoute: typeof LocaleadminRouteRouteWithChildren
  LocalesellerRouteRoute: typeof LocalesellerRouteRouteWithChildren
  LocalestoreRouteRoute: typeof LocalestoreRouteRouteWithChildren
  LocaleAuthForgotPasswordRoute: typeof LocaleAuthForgotPasswordRoute
  LocaleAuthResetPasswordRoute: typeof LocaleAuthResetPasswordRoute
  LocaleAuthVerifyEmailRoute: typeof LocaleAuthVerifyEmailRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleadminRouteRoute: LocaleadminRouteRouteWithChildren,
  LocalesellerRouteRoute: LocalesellerRouteRouteWithChildren,
  LocalestoreRouteRoute: LocalestoreRouteRouteWithChildren,
  LocaleAuthForgotPasswordRoute: LocaleAuthForgotPasswordRoute,
  LocaleAuthResetPasswordRoute: LocaleAuthResetPasswordRoute,
  LocaleAuthVerifyEmailRoute: LocaleAuthVerifyEmailRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
