/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocalestoreRouteRouteImport } from './routes/$locale/(store)/route'
import { Route as LocalesellerRouteRouteImport } from './routes/$locale/(seller)/route'
import { Route as LocaleadminRouteRouteImport } from './routes/$locale/(admin)/route'
import { Route as LocalestoreIndexRouteImport } from './routes/$locale/(store)/index'
import { Route as LocalesellerSellRouteRouteImport } from './routes/$locale/(seller)/sell/route'
import { Route as LocaleadminAdminRouteRouteImport } from './routes/$locale/(admin)/admin/route'
import { Route as LocalestoreSearchIndexRouteImport } from './routes/$locale/(store)/search/index'
import { Route as LocalestoreOrdersIndexRouteImport } from './routes/$locale/(store)/orders/index'
import { Route as LocalestoreFavoritesIndexRouteImport } from './routes/$locale/(store)/favorites/index'
import { Route as LocalestoreCheckoutIndexRouteImport } from './routes/$locale/(store)/checkout/index'
import { Route as LocalestoreCartIndexRouteImport } from './routes/$locale/(store)/cart/index'
import { Route as LocalesellerSellIndexRouteImport } from './routes/$locale/(seller)/sell/index'
import { Route as LocaleadminAdminIndexRouteImport } from './routes/$locale/(admin)/admin/index'
import { Route as LocalestoreShopsShopSlugRouteImport } from './routes/$locale/(store)/shops/$shopSlug'
import { Route as LocalestorePromotionsSlugRouteImport } from './routes/$locale/(store)/promotions/$slug'
import { Route as LocalestoreOrdersOrderIdRouteImport } from './routes/$locale/(store)/orders/$orderId'
import { Route as LocalestoreListingsListingIdRouteImport } from './routes/$locale/(store)/listings/$listingId'
import { Route as LocalestoreCategoriesCategoryIdRouteImport } from './routes/$locale/(store)/categories/$categoryId'
import { Route as LocalesellerSellRegisterRouteImport } from './routes/$locale/(seller)/sell/register'
import { Route as LocalesellerSellDashboardRouteImport } from './routes/$locale/(seller)/sell/dashboard'
import { Route as LocaleadminAdminUsersRouteImport } from './routes/$locale/(admin)/admin/users'
import { Route as LocaleadminAdminShopsRouteImport } from './routes/$locale/(admin)/admin/shops'
import { Route as LocaleadminAdminPromotionsRouteImport } from './routes/$locale/(admin)/admin/promotions'
import { Route as LocaleadminAdminListingsRouteImport } from './routes/$locale/(admin)/admin/listings'
import { Route as LocaleadminAdminDashboardRouteImport } from './routes/$locale/(admin)/admin/dashboard'
import { Route as LocaleadminAdminCategoriesRouteImport } from './routes/$locale/(admin)/admin/categories'
import { Route as LocalestorePaymentsSuccessIndexRouteImport } from './routes/$locale/(store)/payments/success/index'
import { Route as LocalesellerSellOrdersIndexRouteImport } from './routes/$locale/(seller)/sell/orders/index'
import { Route as LocalesellerSellListingsIndexRouteImport } from './routes/$locale/(seller)/sell/listings/index'
import { Route as LocaleadminAdminOrdersIndexRouteImport } from './routes/$locale/(admin)/admin/orders/index'
import { Route as LocalestorePreviewListingsListingIdRouteImport } from './routes/$locale/(store)/preview/listings.$listingId'
import { Route as LocalesellerSellOrdersOrderIdRouteImport } from './routes/$locale/(seller)/sell/orders/$orderId'
import { Route as LocalesellerSellListingsNewRouteImport } from './routes/$locale/(seller)/sell/listings/new'
import { Route as LocalesellerSellListingsListingIdRouteImport } from './routes/$locale/(seller)/sell/listings/$listingId'
import { Route as LocaleadminAdminOrdersOrderIdRouteImport } from './routes/$locale/(admin)/admin/orders/$orderId'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalestoreRouteRoute = LocalestoreRouteRouteImport.update({
  id: '/(store)',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalesellerRouteRoute = LocalesellerRouteRouteImport.update({
  id: '/(seller)',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleadminRouteRoute = LocaleadminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalestoreIndexRoute = LocalestoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalestoreRouteRoute,
} as any)
const LocalesellerSellRouteRoute = LocalesellerSellRouteRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => LocalesellerRouteRoute,
} as any)
const LocaleadminAdminRouteRoute = LocaleadminAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LocaleadminRouteRoute,
} as any)
const LocalestoreSearchIndexRoute = LocalestoreSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => LocalestoreRouteRoute,
} as any)
const LocalestoreOrdersIndexRoute = LocalestoreOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => LocalestoreRouteRoute,
} as any)
const LocalestoreFavoritesIndexRoute =
  LocalestoreFavoritesIndexRouteImport.update({
    id: '/favorites/',
    path: '/favorites/',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreCheckoutIndexRoute =
  LocalestoreCheckoutIndexRouteImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreCartIndexRoute = LocalestoreCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => LocalestoreRouteRoute,
} as any)
const LocalesellerSellIndexRoute = LocalesellerSellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalesellerSellRouteRoute,
} as any)
const LocaleadminAdminIndexRoute = LocaleadminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleadminAdminRouteRoute,
} as any)
const LocalestoreShopsShopSlugRoute =
  LocalestoreShopsShopSlugRouteImport.update({
    id: '/shops/$shopSlug',
    path: '/shops/$shopSlug',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestorePromotionsSlugRoute =
  LocalestorePromotionsSlugRouteImport.update({
    id: '/promotions/$slug',
    path: '/promotions/$slug',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreOrdersOrderIdRoute =
  LocalestoreOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreListingsListingIdRoute =
  LocalestoreListingsListingIdRouteImport.update({
    id: '/listings/$listingId',
    path: '/listings/$listingId',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalestoreCategoriesCategoryIdRoute =
  LocalestoreCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalesellerSellRegisterRoute =
  LocalesellerSellRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocalesellerSellDashboardRoute =
  LocalesellerSellDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocaleadminAdminUsersRoute = LocaleadminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LocaleadminAdminRouteRoute,
} as any)
const LocaleadminAdminShopsRoute = LocaleadminAdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => LocaleadminAdminRouteRoute,
} as any)
const LocaleadminAdminPromotionsRoute =
  LocaleadminAdminPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)
const LocaleadminAdminListingsRoute =
  LocaleadminAdminListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)
const LocaleadminAdminDashboardRoute =
  LocaleadminAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)
const LocaleadminAdminCategoriesRoute =
  LocaleadminAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)
const LocalestorePaymentsSuccessIndexRoute =
  LocalestorePaymentsSuccessIndexRouteImport.update({
    id: '/payments/success/',
    path: '/payments/success/',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalesellerSellOrdersIndexRoute =
  LocalesellerSellOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocalesellerSellListingsIndexRoute =
  LocalesellerSellListingsIndexRouteImport.update({
    id: '/listings/',
    path: '/listings/',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocaleadminAdminOrdersIndexRoute =
  LocaleadminAdminOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)
const LocalestorePreviewListingsListingIdRoute =
  LocalestorePreviewListingsListingIdRouteImport.update({
    id: '/preview/listings/$listingId',
    path: '/preview/listings/$listingId',
    getParentRoute: () => LocalestoreRouteRoute,
  } as any)
const LocalesellerSellOrdersOrderIdRoute =
  LocalesellerSellOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocalesellerSellListingsNewRoute =
  LocalesellerSellListingsNewRouteImport.update({
    id: '/listings/new',
    path: '/listings/new',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocalesellerSellListingsListingIdRoute =
  LocalesellerSellListingsListingIdRouteImport.update({
    id: '/listings/$listingId',
    path: '/listings/$listingId',
    getParentRoute: () => LocalesellerSellRouteRoute,
  } as any)
const LocaleadminAdminOrdersOrderIdRoute =
  LocaleadminAdminOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => LocaleadminAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocalestoreRouteRouteWithChildren
  '/$locale/admin': typeof LocaleadminAdminRouteRouteWithChildren
  '/$locale/sell': typeof LocalesellerSellRouteRouteWithChildren
  '/$locale/': typeof LocalestoreIndexRoute
  '/$locale/admin/categories': typeof LocaleadminAdminCategoriesRoute
  '/$locale/admin/dashboard': typeof LocaleadminAdminDashboardRoute
  '/$locale/admin/listings': typeof LocaleadminAdminListingsRoute
  '/$locale/admin/promotions': typeof LocaleadminAdminPromotionsRoute
  '/$locale/admin/shops': typeof LocaleadminAdminShopsRoute
  '/$locale/admin/users': typeof LocaleadminAdminUsersRoute
  '/$locale/sell/dashboard': typeof LocalesellerSellDashboardRoute
  '/$locale/sell/register': typeof LocalesellerSellRegisterRoute
  '/$locale/categories/$categoryId': typeof LocalestoreCategoriesCategoryIdRoute
  '/$locale/listings/$listingId': typeof LocalestoreListingsListingIdRoute
  '/$locale/orders/$orderId': typeof LocalestoreOrdersOrderIdRoute
  '/$locale/promotions/$slug': typeof LocalestorePromotionsSlugRoute
  '/$locale/shops/$shopSlug': typeof LocalestoreShopsShopSlugRoute
  '/$locale/admin/': typeof LocaleadminAdminIndexRoute
  '/$locale/sell/': typeof LocalesellerSellIndexRoute
  '/$locale/cart/': typeof LocalestoreCartIndexRoute
  '/$locale/checkout/': typeof LocalestoreCheckoutIndexRoute
  '/$locale/favorites/': typeof LocalestoreFavoritesIndexRoute
  '/$locale/orders/': typeof LocalestoreOrdersIndexRoute
  '/$locale/search/': typeof LocalestoreSearchIndexRoute
  '/$locale/admin/orders/$orderId': typeof LocaleadminAdminOrdersOrderIdRoute
  '/$locale/sell/listings/$listingId': typeof LocalesellerSellListingsListingIdRoute
  '/$locale/sell/listings/new': typeof LocalesellerSellListingsNewRoute
  '/$locale/sell/orders/$orderId': typeof LocalesellerSellOrdersOrderIdRoute
  '/$locale/preview/listings/$listingId': typeof LocalestorePreviewListingsListingIdRoute
  '/$locale/admin/orders/': typeof LocaleadminAdminOrdersIndexRoute
  '/$locale/sell/listings/': typeof LocalesellerSellListingsIndexRoute
  '/$locale/sell/orders/': typeof LocalesellerSellOrdersIndexRoute
  '/$locale/payments/success/': typeof LocalestorePaymentsSuccessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocalestoreIndexRoute
  '/$locale/admin/categories': typeof LocaleadminAdminCategoriesRoute
  '/$locale/admin/dashboard': typeof LocaleadminAdminDashboardRoute
  '/$locale/admin/listings': typeof LocaleadminAdminListingsRoute
  '/$locale/admin/promotions': typeof LocaleadminAdminPromotionsRoute
  '/$locale/admin/shops': typeof LocaleadminAdminShopsRoute
  '/$locale/admin/users': typeof LocaleadminAdminUsersRoute
  '/$locale/sell/dashboard': typeof LocalesellerSellDashboardRoute
  '/$locale/sell/register': typeof LocalesellerSellRegisterRoute
  '/$locale/categories/$categoryId': typeof LocalestoreCategoriesCategoryIdRoute
  '/$locale/listings/$listingId': typeof LocalestoreListingsListingIdRoute
  '/$locale/orders/$orderId': typeof LocalestoreOrdersOrderIdRoute
  '/$locale/promotions/$slug': typeof LocalestorePromotionsSlugRoute
  '/$locale/shops/$shopSlug': typeof LocalestoreShopsShopSlugRoute
  '/$locale/admin': typeof LocaleadminAdminIndexRoute
  '/$locale/sell': typeof LocalesellerSellIndexRoute
  '/$locale/cart': typeof LocalestoreCartIndexRoute
  '/$locale/checkout': typeof LocalestoreCheckoutIndexRoute
  '/$locale/favorites': typeof LocalestoreFavoritesIndexRoute
  '/$locale/orders': typeof LocalestoreOrdersIndexRoute
  '/$locale/search': typeof LocalestoreSearchIndexRoute
  '/$locale/admin/orders/$orderId': typeof LocaleadminAdminOrdersOrderIdRoute
  '/$locale/sell/listings/$listingId': typeof LocalesellerSellListingsListingIdRoute
  '/$locale/sell/listings/new': typeof LocalesellerSellListingsNewRoute
  '/$locale/sell/orders/$orderId': typeof LocalesellerSellOrdersOrderIdRoute
  '/$locale/preview/listings/$listingId': typeof LocalestorePreviewListingsListingIdRoute
  '/$locale/admin/orders': typeof LocaleadminAdminOrdersIndexRoute
  '/$locale/sell/listings': typeof LocalesellerSellListingsIndexRoute
  '/$locale/sell/orders': typeof LocalesellerSellOrdersIndexRoute
  '/$locale/payments/success': typeof LocalestorePaymentsSuccessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/(admin)': typeof LocaleadminRouteRouteWithChildren
  '/$locale/(seller)': typeof LocalesellerRouteRouteWithChildren
  '/$locale/(store)': typeof LocalestoreRouteRouteWithChildren
  '/$locale/(admin)/admin': typeof LocaleadminAdminRouteRouteWithChildren
  '/$locale/(seller)/sell': typeof LocalesellerSellRouteRouteWithChildren
  '/$locale/(store)/': typeof LocalestoreIndexRoute
  '/$locale/(admin)/admin/categories': typeof LocaleadminAdminCategoriesRoute
  '/$locale/(admin)/admin/dashboard': typeof LocaleadminAdminDashboardRoute
  '/$locale/(admin)/admin/listings': typeof LocaleadminAdminListingsRoute
  '/$locale/(admin)/admin/promotions': typeof LocaleadminAdminPromotionsRoute
  '/$locale/(admin)/admin/shops': typeof LocaleadminAdminShopsRoute
  '/$locale/(admin)/admin/users': typeof LocaleadminAdminUsersRoute
  '/$locale/(seller)/sell/dashboard': typeof LocalesellerSellDashboardRoute
  '/$locale/(seller)/sell/register': typeof LocalesellerSellRegisterRoute
  '/$locale/(store)/categories/$categoryId': typeof LocalestoreCategoriesCategoryIdRoute
  '/$locale/(store)/listings/$listingId': typeof LocalestoreListingsListingIdRoute
  '/$locale/(store)/orders/$orderId': typeof LocalestoreOrdersOrderIdRoute
  '/$locale/(store)/promotions/$slug': typeof LocalestorePromotionsSlugRoute
  '/$locale/(store)/shops/$shopSlug': typeof LocalestoreShopsShopSlugRoute
  '/$locale/(admin)/admin/': typeof LocaleadminAdminIndexRoute
  '/$locale/(seller)/sell/': typeof LocalesellerSellIndexRoute
  '/$locale/(store)/cart/': typeof LocalestoreCartIndexRoute
  '/$locale/(store)/checkout/': typeof LocalestoreCheckoutIndexRoute
  '/$locale/(store)/favorites/': typeof LocalestoreFavoritesIndexRoute
  '/$locale/(store)/orders/': typeof LocalestoreOrdersIndexRoute
  '/$locale/(store)/search/': typeof LocalestoreSearchIndexRoute
  '/$locale/(admin)/admin/orders/$orderId': typeof LocaleadminAdminOrdersOrderIdRoute
  '/$locale/(seller)/sell/listings/$listingId': typeof LocalesellerSellListingsListingIdRoute
  '/$locale/(seller)/sell/listings/new': typeof LocalesellerSellListingsNewRoute
  '/$locale/(seller)/sell/orders/$orderId': typeof LocalesellerSellOrdersOrderIdRoute
  '/$locale/(store)/preview/listings/$listingId': typeof LocalestorePreviewListingsListingIdRoute
  '/$locale/(admin)/admin/orders/': typeof LocaleadminAdminOrdersIndexRoute
  '/$locale/(seller)/sell/listings/': typeof LocalesellerSellListingsIndexRoute
  '/$locale/(seller)/sell/orders/': typeof LocalesellerSellOrdersIndexRoute
  '/$locale/(store)/payments/success/': typeof LocalestorePaymentsSuccessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/admin'
    | '/$locale/sell'
    | '/$locale/'
    | '/$locale/admin/categories'
    | '/$locale/admin/dashboard'
    | '/$locale/admin/listings'
    | '/$locale/admin/promotions'
    | '/$locale/admin/shops'
    | '/$locale/admin/users'
    | '/$locale/sell/dashboard'
    | '/$locale/sell/register'
    | '/$locale/categories/$categoryId'
    | '/$locale/listings/$listingId'
    | '/$locale/orders/$orderId'
    | '/$locale/promotions/$slug'
    | '/$locale/shops/$shopSlug'
    | '/$locale/admin/'
    | '/$locale/sell/'
    | '/$locale/cart/'
    | '/$locale/checkout/'
    | '/$locale/favorites/'
    | '/$locale/orders/'
    | '/$locale/search/'
    | '/$locale/admin/orders/$orderId'
    | '/$locale/sell/listings/$listingId'
    | '/$locale/sell/listings/new'
    | '/$locale/sell/orders/$orderId'
    | '/$locale/preview/listings/$listingId'
    | '/$locale/admin/orders/'
    | '/$locale/sell/listings/'
    | '/$locale/sell/orders/'
    | '/$locale/payments/success/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/admin/categories'
    | '/$locale/admin/dashboard'
    | '/$locale/admin/listings'
    | '/$locale/admin/promotions'
    | '/$locale/admin/shops'
    | '/$locale/admin/users'
    | '/$locale/sell/dashboard'
    | '/$locale/sell/register'
    | '/$locale/categories/$categoryId'
    | '/$locale/listings/$listingId'
    | '/$locale/orders/$orderId'
    | '/$locale/promotions/$slug'
    | '/$locale/shops/$shopSlug'
    | '/$locale/admin'
    | '/$locale/sell'
    | '/$locale/cart'
    | '/$locale/checkout'
    | '/$locale/favorites'
    | '/$locale/orders'
    | '/$locale/search'
    | '/$locale/admin/orders/$orderId'
    | '/$locale/sell/listings/$listingId'
    | '/$locale/sell/listings/new'
    | '/$locale/sell/orders/$orderId'
    | '/$locale/preview/listings/$listingId'
    | '/$locale/admin/orders'
    | '/$locale/sell/listings'
    | '/$locale/sell/orders'
    | '/$locale/payments/success'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/(admin)'
    | '/$locale/(seller)'
    | '/$locale/(store)'
    | '/$locale/(admin)/admin'
    | '/$locale/(seller)/sell'
    | '/$locale/(store)/'
    | '/$locale/(admin)/admin/categories'
    | '/$locale/(admin)/admin/dashboard'
    | '/$locale/(admin)/admin/listings'
    | '/$locale/(admin)/admin/promotions'
    | '/$locale/(admin)/admin/shops'
    | '/$locale/(admin)/admin/users'
    | '/$locale/(seller)/sell/dashboard'
    | '/$locale/(seller)/sell/register'
    | '/$locale/(store)/categories/$categoryId'
    | '/$locale/(store)/listings/$listingId'
    | '/$locale/(store)/orders/$orderId'
    | '/$locale/(store)/promotions/$slug'
    | '/$locale/(store)/shops/$shopSlug'
    | '/$locale/(admin)/admin/'
    | '/$locale/(seller)/sell/'
    | '/$locale/(store)/cart/'
    | '/$locale/(store)/checkout/'
    | '/$locale/(store)/favorites/'
    | '/$locale/(store)/orders/'
    | '/$locale/(store)/search/'
    | '/$locale/(admin)/admin/orders/$orderId'
    | '/$locale/(seller)/sell/listings/$listingId'
    | '/$locale/(seller)/sell/listings/new'
    | '/$locale/(seller)/sell/orders/$orderId'
    | '/$locale/(store)/preview/listings/$listingId'
    | '/$locale/(admin)/admin/orders/'
    | '/$locale/(seller)/sell/listings/'
    | '/$locale/(seller)/sell/orders/'
    | '/$locale/(store)/payments/success/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(store)': {
      id: '/$locale/(store)'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocalestoreRouteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/(seller)': {
      id: '/$locale/(seller)'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocalesellerRouteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/(admin)': {
      id: '/$locale/(admin)'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleadminRouteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/(store)/': {
      id: '/$locale/(store)/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocalestoreIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(seller)/sell': {
      id: '/$locale/(seller)/sell'
      path: '/sell'
      fullPath: '/$locale/sell'
      preLoaderRoute: typeof LocalesellerSellRouteRouteImport
      parentRoute: typeof LocalesellerRouteRoute
    }
    '/$locale/(admin)/admin': {
      id: '/$locale/(admin)/admin'
      path: '/admin'
      fullPath: '/$locale/admin'
      preLoaderRoute: typeof LocaleadminAdminRouteRouteImport
      parentRoute: typeof LocaleadminRouteRoute
    }
    '/$locale/(store)/search/': {
      id: '/$locale/(store)/search/'
      path: '/search'
      fullPath: '/$locale/search/'
      preLoaderRoute: typeof LocalestoreSearchIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/orders/': {
      id: '/$locale/(store)/orders/'
      path: '/orders'
      fullPath: '/$locale/orders/'
      preLoaderRoute: typeof LocalestoreOrdersIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/favorites/': {
      id: '/$locale/(store)/favorites/'
      path: '/favorites'
      fullPath: '/$locale/favorites/'
      preLoaderRoute: typeof LocalestoreFavoritesIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/checkout/': {
      id: '/$locale/(store)/checkout/'
      path: '/checkout'
      fullPath: '/$locale/checkout/'
      preLoaderRoute: typeof LocalestoreCheckoutIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/cart/': {
      id: '/$locale/(store)/cart/'
      path: '/cart'
      fullPath: '/$locale/cart/'
      preLoaderRoute: typeof LocalestoreCartIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(seller)/sell/': {
      id: '/$locale/(seller)/sell/'
      path: '/'
      fullPath: '/$locale/sell/'
      preLoaderRoute: typeof LocalesellerSellIndexRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(admin)/admin/': {
      id: '/$locale/(admin)/admin/'
      path: '/'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleadminAdminIndexRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(store)/shops/$shopSlug': {
      id: '/$locale/(store)/shops/$shopSlug'
      path: '/shops/$shopSlug'
      fullPath: '/$locale/shops/$shopSlug'
      preLoaderRoute: typeof LocalestoreShopsShopSlugRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/promotions/$slug': {
      id: '/$locale/(store)/promotions/$slug'
      path: '/promotions/$slug'
      fullPath: '/$locale/promotions/$slug'
      preLoaderRoute: typeof LocalestorePromotionsSlugRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/orders/$orderId': {
      id: '/$locale/(store)/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$locale/orders/$orderId'
      preLoaderRoute: typeof LocalestoreOrdersOrderIdRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/listings/$listingId': {
      id: '/$locale/(store)/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/$locale/listings/$listingId'
      preLoaderRoute: typeof LocalestoreListingsListingIdRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(store)/categories/$categoryId': {
      id: '/$locale/(store)/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/$locale/categories/$categoryId'
      preLoaderRoute: typeof LocalestoreCategoriesCategoryIdRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(seller)/sell/register': {
      id: '/$locale/(seller)/sell/register'
      path: '/register'
      fullPath: '/$locale/sell/register'
      preLoaderRoute: typeof LocalesellerSellRegisterRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(seller)/sell/dashboard': {
      id: '/$locale/(seller)/sell/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/sell/dashboard'
      preLoaderRoute: typeof LocalesellerSellDashboardRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(admin)/admin/users': {
      id: '/$locale/(admin)/admin/users'
      path: '/users'
      fullPath: '/$locale/admin/users'
      preLoaderRoute: typeof LocaleadminAdminUsersRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(admin)/admin/shops': {
      id: '/$locale/(admin)/admin/shops'
      path: '/shops'
      fullPath: '/$locale/admin/shops'
      preLoaderRoute: typeof LocaleadminAdminShopsRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(admin)/admin/promotions': {
      id: '/$locale/(admin)/admin/promotions'
      path: '/promotions'
      fullPath: '/$locale/admin/promotions'
      preLoaderRoute: typeof LocaleadminAdminPromotionsRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(admin)/admin/listings': {
      id: '/$locale/(admin)/admin/listings'
      path: '/listings'
      fullPath: '/$locale/admin/listings'
      preLoaderRoute: typeof LocaleadminAdminListingsRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(admin)/admin/dashboard': {
      id: '/$locale/(admin)/admin/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/admin/dashboard'
      preLoaderRoute: typeof LocaleadminAdminDashboardRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(admin)/admin/categories': {
      id: '/$locale/(admin)/admin/categories'
      path: '/categories'
      fullPath: '/$locale/admin/categories'
      preLoaderRoute: typeof LocaleadminAdminCategoriesRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(store)/payments/success/': {
      id: '/$locale/(store)/payments/success/'
      path: '/payments/success'
      fullPath: '/$locale/payments/success/'
      preLoaderRoute: typeof LocalestorePaymentsSuccessIndexRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(seller)/sell/orders/': {
      id: '/$locale/(seller)/sell/orders/'
      path: '/orders'
      fullPath: '/$locale/sell/orders/'
      preLoaderRoute: typeof LocalesellerSellOrdersIndexRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(seller)/sell/listings/': {
      id: '/$locale/(seller)/sell/listings/'
      path: '/listings'
      fullPath: '/$locale/sell/listings/'
      preLoaderRoute: typeof LocalesellerSellListingsIndexRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(admin)/admin/orders/': {
      id: '/$locale/(admin)/admin/orders/'
      path: '/orders'
      fullPath: '/$locale/admin/orders/'
      preLoaderRoute: typeof LocaleadminAdminOrdersIndexRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
    '/$locale/(store)/preview/listings/$listingId': {
      id: '/$locale/(store)/preview/listings/$listingId'
      path: '/preview/listings/$listingId'
      fullPath: '/$locale/preview/listings/$listingId'
      preLoaderRoute: typeof LocalestorePreviewListingsListingIdRouteImport
      parentRoute: typeof LocalestoreRouteRoute
    }
    '/$locale/(seller)/sell/orders/$orderId': {
      id: '/$locale/(seller)/sell/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$locale/sell/orders/$orderId'
      preLoaderRoute: typeof LocalesellerSellOrdersOrderIdRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(seller)/sell/listings/new': {
      id: '/$locale/(seller)/sell/listings/new'
      path: '/listings/new'
      fullPath: '/$locale/sell/listings/new'
      preLoaderRoute: typeof LocalesellerSellListingsNewRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(seller)/sell/listings/$listingId': {
      id: '/$locale/(seller)/sell/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/$locale/sell/listings/$listingId'
      preLoaderRoute: typeof LocalesellerSellListingsListingIdRouteImport
      parentRoute: typeof LocalesellerSellRouteRoute
    }
    '/$locale/(admin)/admin/orders/$orderId': {
      id: '/$locale/(admin)/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$locale/admin/orders/$orderId'
      preLoaderRoute: typeof LocaleadminAdminOrdersOrderIdRouteImport
      parentRoute: typeof LocaleadminAdminRouteRoute
    }
  }
}

interface LocaleadminAdminRouteRouteChildren {
  LocaleadminAdminCategoriesRoute: typeof LocaleadminAdminCategoriesRoute
  LocaleadminAdminDashboardRoute: typeof LocaleadminAdminDashboardRoute
  LocaleadminAdminListingsRoute: typeof LocaleadminAdminListingsRoute
  LocaleadminAdminPromotionsRoute: typeof LocaleadminAdminPromotionsRoute
  LocaleadminAdminShopsRoute: typeof LocaleadminAdminShopsRoute
  LocaleadminAdminUsersRoute: typeof LocaleadminAdminUsersRoute
  LocaleadminAdminIndexRoute: typeof LocaleadminAdminIndexRoute
  LocaleadminAdminOrdersOrderIdRoute: typeof LocaleadminAdminOrdersOrderIdRoute
  LocaleadminAdminOrdersIndexRoute: typeof LocaleadminAdminOrdersIndexRoute
}

const LocaleadminAdminRouteRouteChildren: LocaleadminAdminRouteRouteChildren = {
  LocaleadminAdminCategoriesRoute: LocaleadminAdminCategoriesRoute,
  LocaleadminAdminDashboardRoute: LocaleadminAdminDashboardRoute,
  LocaleadminAdminListingsRoute: LocaleadminAdminListingsRoute,
  LocaleadminAdminPromotionsRoute: LocaleadminAdminPromotionsRoute,
  LocaleadminAdminShopsRoute: LocaleadminAdminShopsRoute,
  LocaleadminAdminUsersRoute: LocaleadminAdminUsersRoute,
  LocaleadminAdminIndexRoute: LocaleadminAdminIndexRoute,
  LocaleadminAdminOrdersOrderIdRoute: LocaleadminAdminOrdersOrderIdRoute,
  LocaleadminAdminOrdersIndexRoute: LocaleadminAdminOrdersIndexRoute,
}

const LocaleadminAdminRouteRouteWithChildren =
  LocaleadminAdminRouteRoute._addFileChildren(
    LocaleadminAdminRouteRouteChildren,
  )

interface LocaleadminRouteRouteChildren {
  LocaleadminAdminRouteRoute: typeof LocaleadminAdminRouteRouteWithChildren
}

const LocaleadminRouteRouteChildren: LocaleadminRouteRouteChildren = {
  LocaleadminAdminRouteRoute: LocaleadminAdminRouteRouteWithChildren,
}

const LocaleadminRouteRouteWithChildren =
  LocaleadminRouteRoute._addFileChildren(LocaleadminRouteRouteChildren)

interface LocalesellerSellRouteRouteChildren {
  LocalesellerSellDashboardRoute: typeof LocalesellerSellDashboardRoute
  LocalesellerSellRegisterRoute: typeof LocalesellerSellRegisterRoute
  LocalesellerSellIndexRoute: typeof LocalesellerSellIndexRoute
  LocalesellerSellListingsListingIdRoute: typeof LocalesellerSellListingsListingIdRoute
  LocalesellerSellListingsNewRoute: typeof LocalesellerSellListingsNewRoute
  LocalesellerSellOrdersOrderIdRoute: typeof LocalesellerSellOrdersOrderIdRoute
  LocalesellerSellListingsIndexRoute: typeof LocalesellerSellListingsIndexRoute
  LocalesellerSellOrdersIndexRoute: typeof LocalesellerSellOrdersIndexRoute
}

const LocalesellerSellRouteRouteChildren: LocalesellerSellRouteRouteChildren = {
  LocalesellerSellDashboardRoute: LocalesellerSellDashboardRoute,
  LocalesellerSellRegisterRoute: LocalesellerSellRegisterRoute,
  LocalesellerSellIndexRoute: LocalesellerSellIndexRoute,
  LocalesellerSellListingsListingIdRoute:
    LocalesellerSellListingsListingIdRoute,
  LocalesellerSellListingsNewRoute: LocalesellerSellListingsNewRoute,
  LocalesellerSellOrdersOrderIdRoute: LocalesellerSellOrdersOrderIdRoute,
  LocalesellerSellListingsIndexRoute: LocalesellerSellListingsIndexRoute,
  LocalesellerSellOrdersIndexRoute: LocalesellerSellOrdersIndexRoute,
}

const LocalesellerSellRouteRouteWithChildren =
  LocalesellerSellRouteRoute._addFileChildren(
    LocalesellerSellRouteRouteChildren,
  )

interface LocalesellerRouteRouteChildren {
  LocalesellerSellRouteRoute: typeof LocalesellerSellRouteRouteWithChildren
}

const LocalesellerRouteRouteChildren: LocalesellerRouteRouteChildren = {
  LocalesellerSellRouteRoute: LocalesellerSellRouteRouteWithChildren,
}

const LocalesellerRouteRouteWithChildren =
  LocalesellerRouteRoute._addFileChildren(LocalesellerRouteRouteChildren)

interface LocalestoreRouteRouteChildren {
  LocalestoreIndexRoute: typeof LocalestoreIndexRoute
  LocalestoreCategoriesCategoryIdRoute: typeof LocalestoreCategoriesCategoryIdRoute
  LocalestoreListingsListingIdRoute: typeof LocalestoreListingsListingIdRoute
  LocalestoreOrdersOrderIdRoute: typeof LocalestoreOrdersOrderIdRoute
  LocalestorePromotionsSlugRoute: typeof LocalestorePromotionsSlugRoute
  LocalestoreShopsShopSlugRoute: typeof LocalestoreShopsShopSlugRoute
  LocalestoreCartIndexRoute: typeof LocalestoreCartIndexRoute
  LocalestoreCheckoutIndexRoute: typeof LocalestoreCheckoutIndexRoute
  LocalestoreFavoritesIndexRoute: typeof LocalestoreFavoritesIndexRoute
  LocalestoreOrdersIndexRoute: typeof LocalestoreOrdersIndexRoute
  LocalestoreSearchIndexRoute: typeof LocalestoreSearchIndexRoute
  LocalestorePreviewListingsListingIdRoute: typeof LocalestorePreviewListingsListingIdRoute
  LocalestorePaymentsSuccessIndexRoute: typeof LocalestorePaymentsSuccessIndexRoute
}

const LocalestoreRouteRouteChildren: LocalestoreRouteRouteChildren = {
  LocalestoreIndexRoute: LocalestoreIndexRoute,
  LocalestoreCategoriesCategoryIdRoute: LocalestoreCategoriesCategoryIdRoute,
  LocalestoreListingsListingIdRoute: LocalestoreListingsListingIdRoute,
  LocalestoreOrdersOrderIdRoute: LocalestoreOrdersOrderIdRoute,
  LocalestorePromotionsSlugRoute: LocalestorePromotionsSlugRoute,
  LocalestoreShopsShopSlugRoute: LocalestoreShopsShopSlugRoute,
  LocalestoreCartIndexRoute: LocalestoreCartIndexRoute,
  LocalestoreCheckoutIndexRoute: LocalestoreCheckoutIndexRoute,
  LocalestoreFavoritesIndexRoute: LocalestoreFavoritesIndexRoute,
  LocalestoreOrdersIndexRoute: LocalestoreOrdersIndexRoute,
  LocalestoreSearchIndexRoute: LocalestoreSearchIndexRoute,
  LocalestorePreviewListingsListingIdRoute:
    LocalestorePreviewListingsListingIdRoute,
  LocalestorePaymentsSuccessIndexRoute: LocalestorePaymentsSuccessIndexRoute,
}

const LocalestoreRouteRouteWithChildren =
  LocalestoreRouteRoute._addFileChildren(LocalestoreRouteRouteChildren)

interface LocaleRouteChildren {
  LocaleadminRouteRoute: typeof LocaleadminRouteRouteWithChildren
  LocalesellerRouteRoute: typeof LocalesellerRouteRouteWithChildren
  LocalestoreRouteRoute: typeof LocalestoreRouteRouteWithChildren
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleadminRouteRoute: LocaleadminRouteRouteWithChildren,
  LocalesellerRouteRoute: LocalesellerRouteRouteWithChildren,
  LocalestoreRouteRoute: LocalestoreRouteRouteWithChildren,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
